// Bundles the Vercel serverless function into ONE self-contained file.
//
// Vercel only ships the api/ directory with the function, so any
// cross-directory import (../server/*) fails at runtime with
// ERR_MODULE_NOT_FOUND. Bundling everything (server code + npm deps)
// into api/[...path].js removes all runtime module resolution.
//
// Output is CJS; api/package.json pins { "type": "commonjs" } so the
// generated .js is treated as CommonJS even though the root project is
// an ES module. Vercel auto-detects api/[...path].js as a Node function.
import { build } from "esbuild";

await build({
  entryPoints: ["server/serverless.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  outfile: "api/[...path].js",
  banner: {
    js: "// GENERATED by script/build-api.mjs — do not edit. Source: server/serverless.ts",
  },
  logLevel: "info",
});

console.log("api/[...path].js bundled");
